### ISSUE TITLE
Syntax on line 113?

### ISSUE THREAD

**Issue by notklaatu** [abhiTamrakar/kube-plugins#5]
When I try to run this, I get this error:

```
$ ./krawl: line 113: syntax error near unexpected token `<'
```

I assume it's meant to be ``done <<($KUBECTL .......)`` ?

**Comment by abhiTamrakar** [comment]
@notklaatu that will be a syntax error doing <<(command), rather the original works fine for me.
Which Shell are you using?
Linux flavour?

Also can you try editing it and replace like below, its basically the same thing, but give it a try and let me know.
```done< <(command)```
with
```done < <(command)```

**Comment by notklaatu** [comment]
Bash on Fedora 31... and it's working. My minikube instance had died without me realizing it, so kubectl was failing, and I guess in the end Bash was picking up the problem as a syntax error. 

Thanks!

**Comment by abhiTamrakar** [comment]
@notklaatu I guess this is something I should handle. I thought of not handling it because it never threw syntax error on me but now it needs more tests to confirm and then I will handle it if needed.
Thanks.
