### ISSUE TITLE
doesnt work ?

### ISSUE THREAD

**Issue by dirtbag** [abhiTamrakar/kube-plugins#8]
**Describe the bug**
script doesnt work with tmux v3 

jason@raspberrypi4 ~ $ kubectl kmux
tmux: option requires an argument -- t
no server running on /tmp/tmux-1000/default

**To Reproduce**
jason@raspberrypi4 ~ $ kubectl kmux 

**Expected behavior**
I expect output about my namespaces/containers/whatnot.

**Screenshots**

jason@raspberrypi4 ~ $ kubectl kmux
tmux: option requires an argument -- t
no server running on /tmp/tmux-1000/default
jason@raspberrypi4 ~ $ 

**Version:**
 - OS: Arch linux  
 - Bash Version: GNU bash, version 5.0.17(1)-release (aarch64-unknown-linux-gnu)

**Additional context**
btw, the tmux config is broke for tmux 3.x as well.. but that's not your fault.. ;)

**Comment by dirtbag** [comment]
actually I went down to tmux 2.8 and it still wont work.. still getting .

jason@raspberrypi4 ~ $ tmux -V
tmux 2.8
jason@raspberrypi4 ~ $ kubectl kmux 
tmux: option requires an argument -- t
no server running on /tmp/tmux-1000/default
jason@raspberrypi4 ~ $

**Comment by abhiTamrakar** [comment]
@dirtbag you were right the config is broken somehow, but it doesn't blocks any functionality, will try to fix when I get time.
BTW the script has some bugs introduced in master somehow, I fixed it.
